networks:
  default:
    driver: bridge
    name: roboshop
    # external: true # if network is already created means we can uncomment this line
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:    
services:
  mongodb:
    image: gsivadvops/mongodb:v1
    container_name: mongodb  
  volumes: 
  - mongodb: /data/db #mounting the volume   
  catalogue:
    image: gsivadvops/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes: 
    - redis: /data #mounting the volume 
  user: 
    image: gsivadvops/user:v1
    container_name: user
    depends_on: 
    - mongodb
    - redis
  cart:
    image: gsivadvops/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: gsivadvops/mysql:v1
    container_name: mysql  
    volumes: 
    - mongodb: /var/lib/mysql #mounting the volume 
  shipping:
    image: gsivadvops/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart 
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes: 
    - mongodb: /var/lib/rabbitmq #mounting the volume    
  payment:
    image: gsivadvops/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user    
  frontend:
    image: gsivadvops/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user  
    - shipping
    - payment  
          